# Google Cloud Build - Backend CI/CD
# Builds Docker image and deploys to Cloud Run
#
# Run from repo root:
#   gcloud builds submit --config=backend/cloudbuild.yaml .
# Or from backend with parent as context:
#   cd backend && gcloud builds submit --config=cloudbuild.yaml ..
#
# Substitutions (set in trigger or default below):
#   _REGION          - Cloud Run region (default us-central1)
#   _SERVICE_NAME    - Cloud Run service name (default health-backend)
#   _IMAGE_TAG       - Tag for image (default latest; use SHORT_SHA in trigger)

substitutions:
  _REGION: northamerica-northeast1
  _SERVICE_NAME: backend
  _IMAGE_TAG: latest
  _CORS_ORIGINS: "https://agentic-ai-home-health-79306395653.europe-west1.run.app,http://localhost:5173"
  # Cloud SQL instance (PROJECT:REGION:INSTANCE)
  _CLOUDSQL_INSTANCE: "tech-83b89:us-central1:healtappdb"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build Docker image
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:${_IMAGE_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:latest
      - .
    dir: backend

  # Push to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:${_IMAGE_TAG}
    waitFor: [build]

  - name: gcr.io/cloud-builders/docker
    id: push-latest
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:latest
    waitFor: [build]

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:${_IMAGE_TAG}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-secrets
      - DATABASE_URL=DATABASE_URL_SECRET:latest,SECRET_KEY=SECRET_KEY_SECRET:latest,DB_PASS=DB_PASS_SECRET:latest
      - --set-env-vars
      - CORS_ORIGINS=${_CORS_ORIGINS},INSTANCE_CONNECTION_NAME=${_CLOUDSQL_INSTANCE},DB_USER=health_user,DB_NAME=health_analytics
      - --add-cloudsql-instances
      - ${_CLOUDSQL_INSTANCE}
    waitFor: [push]
    # Cloud SQL: create DB_PASS_SECRET with DB user password. Create DB and user in instance healtappdb, then run schema (see backend/docs/GCP-DATABASE-CONNECT.md).
    # Note: Create secrets in Secret Manager:
    #   echo -n "postgresql://..." | gcloud secrets create DATABASE_URL_SECRET --data-file=-
    #   echo -n "jwt-secret" | gcloud secrets create SECRET_KEY_SECRET --data-file=-
    #   echo -n "db-user-password" | gcloud secrets create DB_PASS_SECRET --data-file=-

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:${_IMAGE_TAG}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:latest
