# Google Cloud Build - Frontend CI/CD
# Builds Docker image and deploys to Cloud Run
#
# Run from repo root:
#   gcloud builds submit --config=health-app/cloudbuild.yaml .
# Or from health-app with parent as context:
#   cd health-app && gcloud builds submit --config=cloudbuild.yaml ..
# In a trigger, set _IMAGE_TAG to SHORT_SHA for commit-based tags.
#
# Substitutions (set in trigger or default below):
#   _REGION          - Cloud Run region (default us-central1)
#   _SERVICE_NAME    - Cloud Run service name (default health-app)
#   _VITE_API_URL    - Backend API URL at build time (REQUIRED for Cloud Run)
#                      Set to your backend Cloud Run URL: https://health-backend-XXX.run.app
#                      If /api, nginx proxies to BACKEND_URL env var (for local dev)
#   _BACKEND_URL     - Backend URL for nginx proxy (only used if VITE_API_URL=/api)
#   _IMAGE_TAG       - Tag for image (default latest; use SHORT_SHA in trigger)

substitutions:
  _REGION: europe-west1
  _SERVICE_NAME: agentic-ai-home-health
  _VITE_API_URL: https://backend-79306395653.northamerica-northeast1.run.app
  _BACKEND_URL: https://backend-79306395653.northamerica-northeast1.run.app
  _IMAGE_TAG: latest

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build Docker image
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - --build-arg
      - VITE_API_URL=${_VITE_API_URL}
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:${_IMAGE_TAG}
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:latest
      - .
    dir: health-app

  # Push to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:${_IMAGE_TAG}
    waitFor: [build]

  - name: gcr.io/cloud-builders/docker
    id: push-latest
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:latest
    waitFor: [build]

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:${_IMAGE_TAG}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - BACKEND_URL=${_BACKEND_URL}
    waitFor: [push]

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:${_IMAGE_TAG}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:latest
